### PR TITLE
 Add Archlinux build template

### PR DESCRIPTION
**Pull request by Mdyrl7777777**
This adds template for building saractl package in Archlinux.

### CODE REVIEW

**Comment by smeso** [comment]
Please see https://github.com/smeso/sara-test/pull/4

**Comment by Mdyrl7777777** [comment]
I changed it to use git tags. Also I added pgp verification.

**Review by smeso — APPROVED** [review]

**Comment by smeso** [comment]
Thank you very much!

Do you plan to put these PKGBUILDs on AUR?

**Comment by Mdyrl7777777** [comment]
I don't want to deal myself with AUR for now.

**Pull request merged**
